FROM projectatomic/atomicapp:0.1.3

MAINTAINER Dusty Mabe dusty@dustymabe.com

LABEL io.projectatomic.nulecule.specversion=0.0.2 \
      io.projectatomic.nulecule.providers=docker

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts
